"""add delivered_at to orders

Revision ID: a76c844f8be0
Revises: e8f8f62bcb8a
Create Date: 2026-08-31 13:57:31.897071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76c844f8be0'
down_revision: Union[str, Sequence[str], None] = 'e8f8f62bcb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered_at')
    # ### end Alembic commands ###
